[Service]
ExecStartPre=/bin/sh -c 'd=%h/.local/share/krdpserver; [ -s "$d/krdp.crt" ] && [ -s "$d/krdp.key" ] && exit 0; umask 077; mkdir -p "$d" && openssl req -quiet -nodes -new -x509 -keyout "$d/krdp.key" -out "$d/krdp.crt" -days 3650 -batch -subj "/CN=%H"'
ExecStart=
ExecStart=/usr/bin/krdpserver --plasma --virtual-monitor 1280x720@1 --certificate %h/.local/share/krdpserver/krdp.crt --certificate-key %h/.local/share/krdpserver/krdp.key -u user -p user
