#!/bin/sh

if [ -f /etc/os-release ]; then
    . /etc/os-release
    profile_name="${PRETTY_NAME:-Debian}${BUILD_ID:+[${BUILD_ID}]} ${_KERNEL_VERSION}"
else
    profile_name="${_KERNEL_VERSION}"
fi

if has_config FIQ_DEBUGGER_CONSOLE; then
    remove_bootargs "console=ttyS0,1500000n8"
    add_bootargs "console=ttyFIQ0,1500000n8"
fi
