#!/bin/sh

_build_profile_name() {
    local name=""

    if [ -f /etc/os-release ]; then
        . /etc/os-release
        name="${PRETTY_NAME:-Debian}${BUILD_ID:+[${BUILD_ID}]} ${_KERNEL_VERSION}"
    else
        name="${_KERNEL_VERSION}"
    fi

    if [ -n "${U_BOOT_PROFILE_TEMPLATE}" ]; then
        name="$(eval "echo \"${U_BOOT_PROFILE_TEMPLATE}\"")"
    fi

    echo "$name"
}

# Set the base profile name for default and all boards
set_base_profile_name "$(_build_profile_name)"

if has_config FIQ_DEBUGGER_CONSOLE; then
    remove_bootargs "console=ttyS0,1500000n8"
    add_bootargs "console=ttyFIQ0,1500000n8"
else
    add_legend "DEFAULT" "Fake-flipctl on LCD, KDE on HDMI and DisplayPort"
    # Remove first to avoid duplicates if already present in /etc/kernel/cmdline
    remove_bootargs "console=ttyS0,1500000n8"
    add_bootargs "console=ttyS0,1500000n8"
    remove_bootargs "console=ttyFIQ0,1500000n8"
    add_bootargs "fbcon=map:1"
    append_name "[DEFAULT]"
fi
