#!/bin/sh

process_feature() {
    local feature_name=""
    local dtb_added=""

    case "${BASH_SOURCE[0]##*/}" in
        typec-dp)
            feature_name="DP-4K"
            dtb_added=typec-dp-hdmi
            ;;
        typec-hdmi)
            feature_name="HDMI-4K"
            dtb_added=typec-hdmi-dp
            ;;
        *)
            skip_entry=1
            return
    esac

    if has_config ROCKCHIP_DW_DP; then
        add_board_dtbo -z -n "${feature_name}" -d "typec-base" -d "${dtb_added}" \
            -A 'dyndbg="file drivers/gpu/drm/rockchip/dw-dp.c +p"'
    else
        skip_entry=1
    fi
}

process_feature
unset -f process_feature
