#!/bin/sh

process_feature() {
    add_legend "USB NCM" "USB NCM Ethernet gadget"

    if ! has_config USB_CONFIGFS_NCM || ! has_config USB_F_NCM; then
        skip_entry=1
        return
    fi

    add_bootargs systemd.wants=usb-ncm-gadget.service
    add_board_dtbo -e -n "USB NCM" -d "usb-ncm"
}

process_feature
unset -f process_feature
