Syntax 3

SectionVerb {
	EnableSequence [
	]
}

SectionDevice."HDMI" {
	Comment "HDMI"

	Value {
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId}"
		If.1 {
			Condition {
				Type ControlExists
				Control "iface=CARD,name='rockchip-hdmi Jack'"
			}
			True {
				JackControl "rockchip-hdmi Jack"
			}
		}
	}
}

