[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
GreeterEnvironment=KWIN_FORCE_SW_CURSOR=1

[Wayland]
CompositorCommand=kwin_wayland --drm --seat seat0 --no-lockscreen --no-global-shortcuts --locale1