[Distribution]
Distribution=debian
Release=trixie
Architecture=arm64
Repositories=contrib,non-free,non-free-firmware

[Output]
Format=tar
Output=debian-ospack
CompressOutput=no

[Content]
Bootable=no
PostInstallationScripts=mkosi.postinst.chroot
Packages=acl
Packages=adduser
Packages=avahi-daemon
Packages=alsa-ucm-conf
Packages=alsa-utils
Packages=apt-transport-https
Packages=bash-completion
Packages=bc
Packages=bluedevil
Packages=bluez
Packages=bluez-alsa-utils
Packages=bluez-firmware
Packages=bluez-meshd
Packages=bsdextrautils
Packages=bsdmainutils
Packages=build-essential
Packages=ca-certificates
Packages=cec-utils
Packages=cog
Packages=curl
Packages=device-tree-compiler
Packages=dmidecode
Packages=dnsmasq-base
Packages=drm-info
Packages=e2fsprogs
Packages=edid-decode
Packages=evtest
Packages=file
Packages=fio
Packages=firmware-mediatek
Packages=firmware-misc-nonfree
Packages=firmware-realtek
Packages=gcc
Packages=git
Packages=glmark2-wayland
Packages=gpiod
Packages=i2c-tools
Packages=inetutils-telnet
Packages=initramfs-tools
Packages=iperf3
Packages=iproute2
Packages=iptables
Packages=iputils-ping
Packages=iw
Packages=iwd
Packages=kde-config-screenlocker
Packages=kde-spectacle
Packages=kde-standard
Packages=kmscube
Packages=konsole
Packages=kscreen
Packages=less
Packages=libcanberra-pulse
Packages=libdrm-tests
Packages=libtypec-utils
Packages=libubootenv-tool
Packages=libusb-1.0-0-dev
Packages=links
Packages=linux-cpupower
Packages=linux-sysctl-defaults
Packages=lm-sensors
Packages=locales
Packages=lshw
Packages=lsof
Packages=make
Packages=mesa-utils
Packages=modemmanager
Packages=nano
Packages=nftables
Packages=nodejs
Packages=openssh-server
Packages=p7zip
Packages=pciutils
Packages=pipewire-alsa
Packages=plasma-nm
Packages=plasma-systemmonitor
Packages=powercap-utils
Packages=powerdevil
Packages=python3-pandas
Packages=python3-plotly
Packages=rfkill
Packages=rsync
Packages=sddm
Packages=sddm-theme-breeze
Packages=sox
Packages=strace
Packages=stress-ng
Packages=sudo
Packages=sysstat
Packages=systemd
Packages=systemd-repart
Packages=systemd-resolved
Packages=systemd-sysv
Packages=systemd-timesyncd
Packages=systemsettings
Packages=tcpdump
Packages=traceroute
Packages=u-boot-menu
Packages=udev
Packages=unzip
Packages=usb-modeswitch
Packages=usbutils
Packages=util-linux-extra
Packages=v4l-utils
Packages=vim-tiny
Packages=wget
Packages=wireless-regdb
Packages=wireplumber
Packages=wpasupplicant
Packages=zstd
