monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-dp0-sound"
      }
    ]
    actions = {
      update-props = {
        device.description = "Audio"
      }
    }
  }
  {
    matches = [
      {
        device.name = "alsa_card.platform-hdmi-sound"
      }
    ]
    actions = {
      update-props = {
        device.description = "Audio"
      }
    }
  }
]

