monitor.alsa.rules = [
  {
    matches = [
      {
        api.alsa.card.longname = "DP0"
        media.class = "Audio/Device"
      }
    ]
    actions = {
      update-props = {
        device.description = "USB-C1 DisplayPort Audio"
        device.nick        = "DisplayPort"
      }
    }
  },
  {
    matches = [
      {
        api.alsa.card.longname = "HDMI"
        media.class = "Audio/Device"
      }
    ]
    actions = {
      update-props = {
        device.description = "HDMI Audio"
        device.nick        = "HDMI"
      }
    }
  },

  {
    matches = [
      {
        alsa.id = "27ea0000.spdif-tx-spdif-hifi spdif-hifi-0"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "USB-C1 DisplayPort Audio"
        node.nick = "DisplayPort Playback"
      }
    }
  },
  {
    matches = [
      {
        alsa.id = "27d50000.sai-i2s-hifi i2s-hifi-0"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "HDMI Audio"
        node.nick = "HDMI Playback"
      }
    }
  }
]
