# Default-sink priority, low to high: DP0, HDMI, speaker, Bluetooth.
monitor.alsa.rules = [
  # DP0
  {
    matches = [
      {
        alsa.id = "27ea0000.spdif-tx-spdif-hifi spdif-hifi-0"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        priority.session = 400
      }
    }
  },
  # HDMI
  {
    matches = [
      {
        alsa.id = "27d50000.sai-i2s-hifi i2s-hifi-0"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        priority.session = 500
      }
    }
  },
  # Speaker
  {
    matches = [
      {
        alsa.id = "2a620000.sai-nau8822-hifi nau8822-hifi-0"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1000
      }
    }
  }
]

# Bluetooth A2DP nodes appear on connect and vanish on disconnect.
monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "~bluez_output.*"
        media.class = "Audio/Sink"
      }
    ]
    actions = {
      update-props = {
        priority.session = 2000
      }
    }
  }
]
