Syntax 3

SectionVerb {
	EnableSequence [
	]
}

SectionDevice."DP" {
	Comment "DisplayPort"

	Value {
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId}"
		PlaybackChannels 2
		PlaybackRate 44100
		If.1 {
			Condition {
				Type ControlExists
				Control "iface=CARD,name='rockchip-dp0 Jack'"
			}
			True {
				JackControl "rockchip-dp0 Jack"
			}
		}
	}
}

